version: "3.9"
services:
  frontend:
    build: ./ui
    ports:
      - '3000:3000'
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    environment:
      DB_URL: 'mongodb://db:27017/file-share'
    links:
      - db
  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - fileShare:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
volumes:
  fileShare: